<div class="container m-bt-30" id="main_cart_page_div">
       <div class="title-wrapper">
           <p class="title-headings">Terms of service</p>
       </div>
       <div class="row p-3">
       <p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Terms &amp; Conditions of use</span></span></span></u></strong><br />
<span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Your use of the Website and services and tools are governed by the following terms and conditions as applicable to the Website. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transactions. By mere use of the Website, You shall be contracting with Lotuspens.com, these terms and conditions constitute Your binding obligations, with Lotus Writing Instruments.<br />
<br />
For the purpose of these Terms of Use, wherever the context so requires &lsquo;You&rsquo; or &ldquo;User&rdquo; shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. The term &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo; shall mean Lotus.<br />
<br />
<strong><u>Introduction</u></strong><u>:</u></span></span></span></span></span></span></p>

<ol>
	<li><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">www.lotuspens.com website (&quot;Website&quot;) is an Internet-based content and e-commerce portal operated by Lotus Writing Instruments, a company incorporated under the laws of India.</span></span></span></span></span></span></li>
	<li><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Use of the Website is offered to you conditioned on acceptance without modification of all the terms, conditions, and notices contained in these Terms, as may be posted on the Website from time to time. www.lotuspens.com at its sole discretion reserves the right not to accept a User from registering on the Website without assigning any reason thereof.<br />
	<br />
	&nbsp; &nbsp; &nbsp;Please read the following terms and conditions very carefully as your use of service is subject to your acceptance of and compliance with the following terms and conditions (&quot;Terms&quot;).<br />
	<br />
	&nbsp; &nbsp; &nbsp;All products/services and information displayed on Lotuspens.com (&ldquo;Site&rdquo;) constitute an &quot;invitation to offer&quot;. Your order for purchase constitutes your &quot;offer&quot; which shall be subject to the terms and conditions as listed below. Lotuspens.com reserves the right to accept or reject your offer. If you have supplied us with your email address, we will notify you by email as soon as possible to confirm receipt of your order and email you again to confirm details and therefore process the order. Our acceptance of your order will take place upon dispatch of the product(s) ordered. No act or omission of Lotuspens.com prior to the actual dispatch of the product (s) ordered will constitute acceptance of your offer.</span></span></span></span></span></span></li>
</ol>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Membership Eligibility</span></span></span></u></strong><br />
<span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Use of the Site is available only to persons who can form legally binding contracts under applicable law. Persons who are &quot;incompetent to contract&quot; within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents, etc. are not eligible to use the Site. If you are a minor i.e. under the age of 18 years but at least 13 years of age you may use this Site only under the supervision of a parent or legal guardian who agrees to be bound by these Terms and Conditions.<br />
&nbsp;If your age is below that of 18 years your parents or legal guardians can transact on behalf of you if they are registered users. You are prohibited from purchasing any material which is for adult consumption the sale or purchase of which to/by minors are strictly prohibited. Lotuspens.com reserves the right to terminate your membership and refuse to provide you with access to the Site if Lotuspens.com discovers that you are under the age of 18 years.&nbsp;<br />
The Site is not available to persons whose membership has been suspended or terminated by Lotuspens.com for any reason whatsoever. If you are registering as a business entity, you represent that you have the authority to bind the entity to this User Agreement. Unless otherwise specified, the materials on this website are directed solely at those who access this website from India. Those who choose to access this Site from outside India are responsible for compliance with local laws if and to the extent local laws are applicable</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Except where additional terms and conditions are provided which are product specific, these terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the services of Lotuspens.com, you agree to be bound by the Terms and Conditions.<br />
<br />
<strong><u>Account and Registration obligations</u></strong><br />
&quot;Your Information&quot; is defined as any information you provide to us in the registration, buying, or listing process, in the feedback area, or through any e-mail feature. We will protect Your Information in accordance with our privacy policy. If you use the Site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. Lotuspens.com shall not be liable to any person for any loss or damage which may arise as a result of any failure by you to protect your password or account. If you know or suspect that someone else knows your password you should notify us by contacting us immediately through the address provided below. If Lotuspens.com has reason to believe that there is likely to be a breach of security or misuse of Lotuspens.com, we may require you to change your password or we may suspend your account without any liability to Lotuspens.com.<br />
<br />
You also agree to:</span></span></span></span></span></span></p>

<ol>
	<li><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Provide true, accurate, current, and complete information about yourself as prompted by the Lotuspens.com registration form (such information being the &quot;Registration Data&quot;) 2. Maintain and promptly update the Registration Data to keep it true, accurate, current</span></span></span></span></span></span></li>
	<li><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Maintain and promptly update the Registration Data to keep it true, accurate, current, and complete. If you provide any information that is untrue, inaccurate, incomplete, or not current or if Lotuspens.com has reasonable grounds to suspect that such information is untrue, inaccurate, not current, or not in accordance with the User Agreement, Lotuspens.com has the right to indefinitely suspend or terminate your membership and refuse to provide you with access to the Site</span></span></span></span></span></span></li>
</ol>

<p><span style="font-size:24pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong><span style="font-family:&quot;var(--typeHeaderFallback)&quot;,serif"><span style="color:#272626">Privacy policy</span></span></strong></span></span></span></p>

<p><span style="font-size:12pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Privacy Policy</span></span></span></strong><br />
<span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp;Thank you for visiting our website. This privacy policy tells you how we use personal information collected at this site. Please read this privacy policy before using the site or submitting any personal information. By using the site, you are accepting the practices described in this privacy policy. These practices may be changed, but any changes will be posted and changes will only apply to activities and information on a going forward, not retroactive basis.</span></span></span></span></span></span></p>

<p><br />
<span style="font-size:12pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626"><strong><span style="font-family:&quot;Arial&quot;,sans-serif">We protect your privacy.</span></strong><br />
&nbsp; &nbsp; &nbsp;Our privacy policy is simple: any information you give us stays with us. We do not rent, sell, lend, or otherwise distribute your personal information to anyone for any reason. This includes your contact information, as well as specific order information.<br />
<br />
<strong><span style="font-family:&quot;Arial&quot;,sans-serif">We limit data access to those who need to know.</span></strong><br />
&nbsp;&nbsp;&nbsp;&nbsp; Within our organization, your personal data is accessible to only a limited number of employees with special access privileges. Although we may, from time to time, compile general demographic information based on your order, this information is shared within our organization only and has no identifiable personal data associated with it.<br />
<br />
<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Information Collected</span></strong><br />
&nbsp; &nbsp; &nbsp;To enable you to place an order on our site, we need to have the following basic information about you: Your First Name, Your Last Name, and Your Address, City, Zip code, State, Country, Phone Number, and Contact E-mail address.<br />
<br />
<br />
<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Cookie/Tracking Technology</span></strong><br />
&nbsp; &nbsp; &nbsp;The Site may use cookie and tracking technology depending on the features offered. Cookie and tracking technology are useful for gathering information such as browser type and operating system, tracking the number of visitors to the Site, and understanding how visitors use the Site. Cookies can also help customize the Site for visitors. Personal information cannot be collected via cookies and other tracking technology, however, if you previously provided personally identifiable information, cookies may be tied to such information. Aggregate cookie and tracking information may be shared with third parties.<br />
&nbsp; &nbsp; &nbsp;We do not allow any unauthorized person or organization be it other members, visitors, and anyone not in our organization to use any information collected from you.<br />
<br />
<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Information Modification</span></strong><br />
&nbsp; &nbsp; &nbsp;You can modify your personal details by accessing the Edit Profile option anytime from our site.<br />
<br />
<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Information Sharing</span></strong><br />
&nbsp; &nbsp; &nbsp;Probably this is the most important question in your mind as to with whom do we share your information? The answer to this question is that we do not rent, sell, barter, or give away your information to anyone. To some extent, information has to be passed on to the courier companies, credit card processing companies, vendors, etc. to enable them to perform their functions related to your order fulfillment.<br />
&nbsp; &nbsp; &nbsp;Apart from this normal business requirement, information may also be needed to be shared with law authorities.&nbsp;We may share information with governmental agencies or other companies assisting us in fraud prevention or investigation. We may do so when: (1) permitted or required by law; or, (2) trying to protect against or prevent actual or potential fraud or unauthorized transactions; or, (3) investigating fraud that has already taken place. The information is not provided to Private or Public&nbsp;companies for marketing purposes.<br />
<br />
<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Information Usage</span></strong><br />
&nbsp; &nbsp; &nbsp;The most important usage of the information collected from you is your email ID and Mobile number, which are used to inform you that your order has been confirmed/executed. Your email is also used to inform you of your customer service-related queries and for any newsletters sent. All other information collected is confidentially stored and will not be disclosed unless needed as per the requirement of the law authorities or in case of any disputes.<br />
<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Note:&nbsp;</span></strong>The privacy practices set forth in this privacy policy are for www.lotuspens.com only. If you link to other websites, please review the privacy policies posted at those sites.</span></span></span></span></span></span></p>

<p><span style="font-size:12pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp;<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Commitment to Data Security</span></strong><br />
&nbsp; &nbsp; &nbsp; Your personally identifiable information is kept secure. Only authorized employees, agents, and contractors (who have agreed to keep information secure and confidential) have access to this information. All emails and newsletters from this site allow you to opt-out of further mailings.<br />
&nbsp;</span></span></span></span></span></span></p>

<p><span style="font-size:12pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Privacy Contact Information</span></span></span></strong></span></span></span></p>

<p><span style="font-size:12pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp;Lotuspens has all the rights to update/modify the mentioned terms and conditions in the policy from time to time to ensure better service to connoisseurs time and again. For any reason, you find any policy term causing a hindrance to your purchasing decision, do write to us at&nbsp;info@lotuspens.in We would review the same and come up with an amicable solution. </span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:24.0pt"><span style="font-family:&quot;var(--typeHeaderFallback)&quot;,serif"><span style="color:#272626">Shipping policy</span></span></span></strong></span></span></span></p><br/>

<div class="row">
<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Shipping rates &amp; costs:</span></span></span></u></strong></span></span></span></p>
</div>


<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; Within India, we charge a delivery free, however for orders of any accessories like Clips, Kimono, Boxes, Stands etc we charge a delivery fee of INR 150.</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; International shipping is calculated dditional at $25 for all orders..&nbsp;</span></span></span><strong><u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#2b00ff">For orders pen 3 and above we don&rsquo;t charge a shipping fee.</span></span></span></u></strong><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp;This is applicable to standard packaged pens.</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; Please note, In the case of International shipments we are not responsible for payment of destination-specific local duties and taxes. Please do your due diligence before placing orders. To clarify doubts, regarding international shipping, please get in touch with our customer care through the WhatsApp chat option.&nbsp;</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Shipping methods and delivery times and tracking:</span></span></span></u></strong></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; &nbsp;For shipping within India, we have partnered with leading courier and delivery companies like&nbsp;<strong><u>Blue Dart, Anjani </u></strong>etc. The Courier partner for any particular Indian Pin code depends on the availability of service of any of the provided service partners. The pens are customized and shall take about 3 to 4 weeks to dispatch once the order is placed subject to available to the material. Once the shipment process is started, you would start receiving automated email and SMS updates with tracking details, from our Shipping management partners. We usually ship products only through Airfreight that reach a destination in 2 to 4 working days.</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; For Shipping to International addresses, our preferred courier partners are&nbsp;<strong><u>DHL</u></strong>. Which usually takes around 8 to 10 working days</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;To still get further details, please get in touch with over email on </span></span></span><span style="color:black"><a href="mailto:info@lotuspens.in" style="color:blue; text-decoration:underline"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif">info@lotuspens.in</span></span></a></span><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626"> our&nbsp;<strong><u>customer care team shall revert at earliest </u></strong></span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Shipping restrictions:</span></span></span></u></strong></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; For Shipments within India and Internationally, we don&rsquo;t have any restrictions in place. If at all, any arise due to non-accessibility of any particular region or city, our support team will coordinate to find the best alternative.</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626"><strong><u>Missing or lost packages:</u></strong></span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; In very rare and unpredictable circumstances, a package is lost during transit. We would wait for a period of 30 days to complete the process of tracking and re-shipping to your right address, failing which we would give a refund at the end of 30 days.</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626"><strong><u>PRE-ORDER Products Shipping Policy</u>:</strong></span></span></span></span></span></span></p>

<p><span style="font-size:24pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong><span style="font-family:&quot;var(--typeHeaderFallback)&quot;,serif"><span style="color:#272626">Privacy policy</span></span></strong></span></span></span></p>
<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; Thank you for considering Lotuspens for customizing your pen. At Lotuspens we value every order and strive to make it available as soon as possible. Nonetheless most of these pen blanks are from International brands and we may face certain unexpected&nbsp;</span></span></span><u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#196ac2">challenges which may hinder timely delivery or no delivery</span></span></span></u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">. The usual delivery period for a pen vary from&nbsp;</span></span></span><u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#245fa1">3-4 weeks </span></span></span></u><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Under very rare circumstances, when blanks are sold out at the time of Order or when delivery is delayed beyond our control, we may ask you to extend the committed delivery time or we may be forced to cancel the order, as the situation may be. Under such events, we will issue a full refund of the amount paid to us.&nbsp;</span></span></span></span></span></span></p>

<p><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">&nbsp; &nbsp; &nbsp; Lotuspens has all the rights to update/modify the mentioned terms and conditions in the policy from time to time to ensure better service to connoisseurs time and again. For any reason, you find any policy term causing a hindrance to your purchasing decision, do write to us at&nbsp;</span></span></span><span style="color:black"><a href="mailto:info@lotuspens.in" style="color:blue; text-decoration:underline"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif">info@lotuspens.in</span></span></a></span><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626"> &nbsp;We would review the same and come up with an amicable solution. All legal matters are subjected to Mumbai jurisdiction only and will be heard in the Mumbai court of law.</span></span></span></span></span></span></p>

<p>&nbsp;</p>

<p><strong><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Return And exchange Policy</span></span></span></span></span></strong></p>

<ol>
	<li><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">Since all the pens are customized will not be accept for exchange or return.</span></span></span></span></span></span></li>
	<li><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">If you are not sure of the exact usage or know-how about the product received, we will guide you on the usage of the product. Please share the details with our master Craftsman via email on </span></span></span></span><span style="color:black"><a href="mailto:info@lotuspens.in" style="color:blue; text-decoration:underline"><span style="font-size:13.5pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Arial&quot;,sans-serif">info@lotuspens.in</span></span></span></a></span><span style="font-size:13.5pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626"> we will get back to you with the right product usage guidelines.</span></span></span></span></span></span></span></li>
	<li><span style="font-size:11pt"><span style="background-color:#fafaf7"><span style="font-family:Calibri,sans-serif"><span style="font-size:13.5pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626">We value our customers a lot and will go out of the way to solve all and any queries, as far as possible and that does not harm Lotuspens. Being in this trade since 2017 also gives us ample experience, knowledge on the products we deal in and the possible issues that may arise. We certainly hope there is little or no scope of any confrontation. we will try our maximum to solve all matters amicably.<br />
	Trusting in you and ensuring we provide the best pre and post-buying experience.</span></span></span></span><br />
	<span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626"><span style="background-color:#fafaf7">&nbsp; &nbsp; &nbsp;Lotuspens has all the rights to update/modify the mentioned terms and conditions in the policy from time to time to ensure better service to connoisseurs time and again. For any reason, you find any policy term causing a hindrance to your purchasing decision, do write to us at&nbsp;</span></span></span></span><span style="color:black"><a href="mailto:info@lotuspens.in" style="color:blue; text-decoration:underline"><span style="font-size:13.5pt"><span style="font-family:&quot;Arial&quot;,sans-serif">info@lotuspens<span style="background-color:#fafaf7">.in</span></span></span></a></span><span style="font-size:13.5pt"><span style="background-color:#fafaf7"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:#272626"> &nbsp;We would review the same and come up with an amicable solution. All legal matters are subjected to Mumbai jurisdiction only and will be heard in the Mumbai court of law.</span></span></span></span></span></span></span></li>
</ol>
       </div>
   </div>